services:
  parthos-user-api:
    container_name: parthos-user-api
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      npm install &&
      npm run start:dev
      "
    networks:
      - parthos-network 

  db:
    image: postgres:14-alpine
    container_name: parthos-user-db
    ports:
      - "5433:5432" 
    environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
    POSTGRES_DB: ${DB_NAME}
    volumes:
      - parthos-data:/var/lib/postgresql/data
    networks:
      - parthos-network
    ports:
      - "${DB_PORT}:${DB_PORT}" 
volumes:
  parthos-user-data:

networks:
  parthos-network:
    external: true
